### ISSUE TITLE
Installation and running the program

### ISSUE THREAD

**Issue by starhopp3r** [naturalstupid/PyHora#1]
Hi, is this repository up to date? I tried installing the package through setup.py but it doesn't install at all. There are issues with the installation script.

**Comment by naturalstupid** [comment]
I use eclipse IDE. and never used a python package from command line using setup.py
Change in setup.py
`package_info_file_path = os.path.join(os.path.dirname(__file__), "hora", "_package_info.py")`
to 
`package_info_file_path = os.path.join(os.path.dirname(__file__), "./", "_package_info.py")`
And in _package_info.py
remove standard pacjages from install_requires and simply use:
`install_requires = ['swisseph', 'geopy','pytz','PyQt6' ]`

**Comment by MridulKabra** [comment]
@naturalstupid I want to connect with you regarding a software request, how can we connect? 
My email id is mridul.kabra23@gmail.com and my WhatsApp number is 9314512233

**Comment by Akilesh1989** [comment]
Hi @naturalstupid is there a instruction manual to get the app running? We're running into multiple issues during setup and execution. We assumed we should simply start the `panchanga.py` file to run the app. But that doesn't seem to work. The command we used was,

```
python3 hora/panchanga/panchanga
```
and the error we got was,
```
panchanga_date Date(year=1996, month=12, day=7)
Traceback (most recent call last):
  File "/Users/akilesh/Documents/greyfeathers/consulting/baaz/horoscopes/PyHora/hora/panchanga/panchanga.py", line 1482, in <module>
    print(tamil_month_and_date(Date(1996,12,7), place))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akilesh/Documents/greyfeathers/consulting/baaz/horoscopes/PyHora/hora/panchanga/panchanga.py", line 1401, in tamil_month_and_date
    sunset_jd = sunset(jd, place)[2]
                ^^^^^^^^^^^^^^^^^
  File "/Users/akilesh/Documents/greyfeathers/consulting/baaz/horoscopes/PyHora/hora/panchanga/panchanga.py", line 364, in sunset
    result = swe.rise_trans(jd_utc - tz/24, swe.SUN, lon, lat, rsmi = _rise_flags + swe.CALC_SET)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer
```

Could you please provide a short step by step manual to get the code up and running?

**Comment by naturalstupid** [comment]
The above error is likely related to API Change in Swiss Ephemeris.
in swe.rise_trans function change the arguments from ,lon,lat, - to - ,geopos=(lon, lat,0.0),
I dont remeber what other changes swiss ephemeris have made in their latest version. I will upload soon a later version of PyHora.
With regards to installation manual. In the main page I have already provided UI instructions (you will need PyQt)
I have always used Eclipse IDE and know it works there as eclipse project. I have not tried command line of individual modules.
Hope that helps
